title: Resonance
description: Cognitive and diegetic framework for TTRPGs
baseurl: "/resonance"
url: "https://aleascript.github.io"
permalink: pretty
theme: jekyll-theme-cayman
lang: en
author: AleaScript

languages: ["en", "fr"]

twitter:
  card: summary

logo: /content/assets/resonance.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - tools/
  - git-hooks/
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: /content/assets/resonance.png
  - scope:
      path: "content/en"
    values:
      lang: en
  - scope:
      path: "content/fr"
    values:
      lang: fr
